export * from './conexao';
export * from './erros';
export * from './fila-adaptador';
export * from './schema';
export * from './withClinic';

export * as agenda from './repos/agenda';
export * as atrasos from './repos/atrasos';
export * as alertas from './repos/alertas';
export * as conexao from './repos/conexao';
export * as conversas from './repos/conversas';
export * as fila from './repos/fila';
export * as hoje from './repos/hoje';
export * as ia from './repos/ia';
export * as financeiro from './repos/financeiro';
export * as numeros from './repos/numeros';
export * as operador from './repos/operador';
export * as pacientes from './repos/pacientes';
export * as procedimentos from './repos/procedimentos';
export * as qualificacao from './repos/qualificacao';
export * as profissionais from './repos/profissionais';
export * as acoes from './repos/acoes';
export * as envios from './repos/envios';
